language: node_js
node_js:
  - 0.6
  - 0.7
notifications:
  email:
    - ted@radicaldesigns.org 
    - cooperq@cooperq.com
before_script:
  - mysql -uroot < test/test.sql
  - cp test/config-test.js ../config.js

