language: node_js
node_js:
  - 0.6
  - 0.8
after_install:
  - "export DISPLAY=:99.0"
  - "export NODE_ENV=test"
  - "sh -e /etc/init.d/xvfb start"
  - "npm start & > /dev/null"
  - "java -jar lib/test/lib/selenium-server-standalone-2.21.0.jar & > /dev/null"
notifications:
  email:
    - ted@radicaldesigns.org 
    - cooperq@cooperq.com
before_script:
  - mysql -uroot < examples/db.sql
